### ISSUE TITLE
Audio is lost

### ISSUE THREAD

**Issue by tatellos** [mallorbc/whisper_mic#10]
Hello friend! Thank you for your great initiative with this repository, it's very useful!
However, I noticed that because the call to the model is a blocking call, the voice input during the time the AI model is working is lost.
In a private repo I fixed this with threading and queues, would you be interested in a Pull Request for this repo as well?

**Comment by mallorbc** [comment]
Hi!  Glad you found this useful. I am definitely open to PRs.  I will be approving the currently open PR soon and could review yours as well.
