### ISSUE TITLE
Need help understanding the inputs

### ISSUE THREAD

**Issue by n-srinidhi** [mallorbc/whisper_mic#12]
Hey!Thanks a lot for the implementation!Its simple and super useful. Can you explain the following conversion:

`torch_audio = torch.from_numpy(np.frombuffer(audio.get_raw_data(), np.int16).flatten().astype(np.float32) / 32768.0)`

Why do we need to convert it to float 32?

**Comment by mallorbc** [comment]
Thats the type of tensor the model expects

**Comment by n-srinidhi** [comment]
Thank you!
