### ISSUE TITLE
Wish: save audio recording in a file to accompany the corresponding transcription

### ISSUE THREAD

**Issue by yubrshen** [mallorbc/whisper_mic#13]
I find that whisper is not that accurate for my English. I wish to have the capability to save the audio so that I can play back and correct the transcription. (This is the practice of otter.ai). I don't really need a real-time transcription. It's fine for me to record it, and get the transcription later, hopefully with the audio recording of the original.

I wish it would be even cooler to use my correction to improve whisper for my own situation. I'm not sure if it is possible currently.

**Comment by yubrshen** [comment]
I'm willing to try to implement the new requirements. Any suggestion or pointer is appreciated.

**Comment by mallorbc** [comment]
Does the --save_file flag not do what you want?

**Comment by mallorbc** [comment]
Pretty sure this does what you want. Reopen if not.
