### ISSUE TITLE
Not Using GPU (Windows)

### ISSUE THREAD

**Issue by Matiusauce** [mallorbc/whisper_mic#18]
Running on windows via miniconda3. I am using the large model and it is not touching my VRAM, just spiking my CPU to about 50%.

Not seeing any flags to specify CPU vs GPU via help and not seeing anywhere in the code that specifies it.

**Comment by nopalfi** [comment]
I loaded the whisper to the GPU just fine in windows. It has to be something with your torch version package, make sure its not for CPU only. Try
```
import torch
torch.cuda.is_available()
```
if it's return False, then you installed incorrect version of torch, or GPU doesn't detect your CUDA.
Try install pytorch from [pytorch.org](https://pytorch.org/) and make sure you can see your CUDA version with 'nvidia-smi.exe'
I have CUDA version 1.12 but i can install pytorch with 1.18 just fine

**Comment by mallorbc** [comment]
Will be looking at this PR soon

**Comment by mallorbc** [comment]
This will now work if there are no issues with torch and cuda is available
