### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by sswam** [mallorbc/whisper_mic#19]
Could you please consider using a less restrictive license, such as MIT? I mean, the whisper repo itself is MIT licensed. As it is, I'm not willing to reuse your code. I would have to rewrite it, which frankly is trivial these days using GPT.

Can you offer MIT as an alternative license please, so that I can use your code directly and give you credit for it?

**Comment by Joelmmm** [comment]
I agree

**Comment by TonyMajorDev** [comment]
I am fine with MIT license.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by tatellos** [comment]
I am also fine with MIT license

**Comment by DevenBL** [comment]
The less restrictive the license the better any license less restrictive i would agree to

**Comment by mallorbc** [comment]
This is done
