### ISSUE TITLE
Error when attempting to use speaker audio

### ISSUE THREAD

**Issue by ReddKarma** [mallorbc/whisper_mic#22]
I've been trying to get this to recognise speech from the audio output of my headphone speakers, I found the correct device index and set it but it gives me this error whenever i try using a speaker instead of a microphone

```
line 465, in listen
    assert source.stream is not None, "Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?"
AssertionError: Audio source must be entered before listening, see documentation for ``AudioSource``; are you using ``source`` outside of a ``with`` statement?
```

here is a snippet of the code:

```    
with sr.Microphone(sample_rate=16000, device_index=6) as source:
        print("Say something")
        i = 0
        while True:
            audio = r.listen(source)
```

I didn't change anything big aside from adding comments and setting a device index for my speakers. the error points to the last line
`audio = r.listen(source)`

**Comment by mallorbc** [comment]
It works with the change you made?  Perhaps an argument to pass would be allowing one to set the device index

**Comment by mallorbc** [comment]
We now allow passing of device indexes but we use the default device by default.  Thus this issue should be good.  Reopen if not.
