### ISSUE TITLE
Massive blocks of text – can this stream out smaller/consistent chunks?

### ISSUE THREAD

**Issue by Toxotei** [mallorbc/whisper_mic#23]
This works really well for transcribing standalone sentences. However, if you read from a book, for example, and don't leave a substantial amount of silent space after finishing a sentence, it won't process the results of what you say until after you finish speaking and will then print a massive block of text. 

Is there something that can be done to push whisper to output smaller blocks of text, or to slice the audio going into the transcriber, in order to encourage it to stream out smaller chunks of text (at least at approximately the sentence level, since word-level might be asking too much)? I notice the GPU idling until I finish talking, so I don't think it's doing most of the transcription work until that point, and I'd like to better utilize my GPU as I speak.

**Comment by mallorbc** [comment]
I think it would make sense to start processing after 30 seconds, as that is what is going on behind the scenes(30 seconds at a time).

This is not currently supported, but I hope that maybe one day it will be.  Looking to have others help with this.

**Comment by mallorbc** [comment]
This is now supported
