### ISSUE TITLE
[Speech not recognized] it stops at `audio = r.listen(source)` 

### ISSUE THREAD

**Issue by manami-bunbun** [mallorbc/whisper_mic#31]
Hello, firstly, thank you for the development!

This could be a hardware issue rather than code, but I would like to ask you a question as no matter how many solutions I have tried, it does not resolve the issue.

## Issue
Sometimes the voice is not recognized for about 2 hours.

## Where the problem occurs
In cli.py, line 51, `audio = r.listen(source)` in `record_audio()` does not work.

## Environment
Macbook M2 Air, (I tried python3.9, 3.10, 3.11)

## Steps so far

After the first smooth use of whisper-mic, it stopped working about 24 hours later.
For that, the following method works occasionally.

- `pip install whisper-mic` again
- turn off permission for microphone once from control panel on macbook and turn it on and restart 
However, even if it works occasionally with these methods, it stops after about 2 hours.

The following methods did not work.
* simply restart 
* shut down macbook and wait for 1mins , then start (for pram things)
* reduce noise reduction (`r.adjust_for_ambient_noise(source,duration=1)`)
	
* Specify device_index, with sr.Microphone(device_index = None / also in 3 after checking)
	
* For [Speech recognition](https://github.com/Uberi/speech_recognition), `python3 -m speech_recognition` used in sr part doesn't work either
	
* Create an environment with venv and try again -> it stops with "say something...".
	
* Create an environment with pipenv and try again -> stops with "say something..." * Create an environment with docker and try again -> stops with "say something...
	
* Create an environment with docker and try again

I've been stuck in this problem for 3 weeks. 
I appreciate your any help！!

**Comment by mallorbc** [comment]
Does this still happen with the latest release?

**Comment by mallorbc** [comment]
I believe it is likely that #83 fixed this issue.  Reopen if not
