### ISSUE TITLE
Set Microphone to Use

### ISSUE THREAD

**Issue by jonfairbanks** [mallorbc/whisper_mic#35]
Thank you for writing this package. Very useful!

I am running this on my Macbook and using the built-in mic works fine, but the quality is not that great.

I purchased a USB C conference mic which I can see in System Preferences > Input but it seems the script still wants to use the built-in mic. 

Is it possible to override the mic that is used and point it towards my USB mic?

**Comment by jonfairbanks** [comment]
Looks like this is possible via Speech Recognizer library: https://stackoverflow.com/questions/68544649/python-speech-recognition-change-between-microphones

**Comment by mallorbc** [comment]
I will add this as an option when I get the chance.  Else if you make a PR, I will review and merge it.

Thanks!

**Comment by mallorbc** [comment]
This is resolved

**Comment by jonfairbanks** [comment]
Thanks a bunch!
