### ISSUE TITLE
Unable to capture audio

### ISSUE THREAD

**Issue by winniehar** [mallorbc/whisper_mic#4]
Hi. I tried using mic following your video tutorial but got this error.
    `File "C:\whisper_mic\whisper\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)  `  
    `File "C:\Users\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in _init_
    self._execute_child(args, executable, preexec_fn, close_fds,  `
    `File "C:\Users\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child  
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,  `
    `FileNotFoundError: [WinError 2] The system cannot find the file specified`

I found [this](https://stackoverflow.com/questions/73193119/python-filenotfounderror-winerror-2-the-system-cannot-find-the-file-specifie) and went ahead to change the shell parameter in POpen init to True and ended up with another error. 

`File "C:\winni\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  `
  `File "C:\Users\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None  `
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

It seems to me like no audio is captured. I also tried using a headset but it still doesn't work. Would you be able to help?
I'm using Windows 10 and Python 3.10.4

**Comment by mallorbc** [comment]
It sounds like to me you may be missing some libs like how I had to run the command under Troubleshooting on Ubuntu.

It also may be a 3.10 issue, not sure though.  Whisper was made with 3.9.

**Comment by mallorbc** [comment]
Do you have ffmpeg installed and added to the path?

**Comment by winniehar** [comment]
I'm not sure what I did differently but I tried again by creating another virtual environment and this time it works just fine! I had ffmpeg installed and added to path both times. But what I can be sure is Python 3.10.4 + Windows 10 will not be an issue.
Thank you for following up! I'll close the issue :)
