### ISSUE TITLE
Stop listening after a period of silence 

### ISSUE THREAD

**Issue by pawelk1337** [mallorbc/whisper_mic#42]
if its listening for example `result = mic.listen(timout=6)` make it so it automaticly stops after a `silence_timeout` (deflaut 1.5s)

**Comment by pawelk1337** [comment]
BTW you can add an ability to change the lang to one (example  `mic = WhisperMic(model="large", lang="polish")`)

**Comment by mallorbc** [comment]
PR #47 fixes the listen issue you are describing here but introduces issues with listen_loop.  I will merge that PR when I or someone else fixes those issues.

Thanks!
