### ISSUE TITLE
How to terminate program

### ISSUE THREAD

**Issue by arschoon** [mallorbc/whisper_mic#45]
Hello!

How does the new version of your program handle stopping the live transcription? I haven't been able to find where the terminating key stroke is defined, apologies if I have overlooked this. I have been killing the process manually in my cli.

Thank you

**Comment by mallorbc** [comment]
Ctrl C is the correct way.

**Comment by ruslanguns** [comment]
Ctrl+C works fine when you can use the keyboard, but having a method to stop transcriptions directly is way better. It lets the transcription process end with the thread when needed, making the system more reliable and flexible.
