### ISSUE TITLE
no transcript output

### ISSUE THREAD

**Issue by bhanna-ux** [mallorbc/whisper_mic#50]
hello ,

i have run everthing according your tutorial but when i run the code : 
whisper-mic --model small -- loop 

nothing transcript from my voice .i use the built-in mic of laptop

**Comment by mallorbc** [comment]
What about non loop?

**Comment by mallorbc** [comment]
I believe that with #83 this issue should either be resolved or be a hardware issue.  Please reopen if not

**Comment by Ayushhkkux** [comment]
Just showing Listening... in my anaconda powershell prompt.
But I cant get the transcription ,.... actually it is showing nothing,,,
By the way 1st time it works but today I tried a lot of times making a tonnes of venv i cant resolve this....
OS:- windows11
The 2 simple steps still coughing to me...🥲😔 help me developer
