### ISSUE TITLE
cannot import the function to another project 

### ISSUE THREAD

**Issue by bhanna-ux** [mallorbc/whisper_mic#51]
i success to import whisper_mic 
but whisper_mic.whisper_mic Cloudnet find as attached 

![image](https://github.com/mallorbc/whisper_mic/assets/114748994/0f668a4a-271d-428a-9395-b5e45759fe20)

**Comment by mallorbc** [comment]
You pip install this?

**Comment by mallorbc** [comment]
If this was an issue, it is fixed.  I have pip installed it and used the software.  You now import it with a shorter path though
