### ISSUE TITLE
Takes considerable time to actually setup the mic and start transcribing

### ISSUE THREAD

**Issue by overlordiam** [mallorbc/whisper_mic#52]
It takes about 8-10 seconds for the program to print "Mic setup". Just wondering why there is a delay. Is it because of the whisper model or because of the mic setup itself? Is there anyway to improve the load time, if done, can enhance the project greatly. I am willing to look into it, so any leads are welcomed.

**Comment by mallorbc** [comment]
We load the model then setup the mic.  Its probably due to the time loading the model.  You can tell if this is the main thing if smaller models load quicker.  Using a faster SSD and CPU would help here.
