### ISSUE TITLE
[Fix] Keyboard interrupt for listen_loop

### ISSUE THREAD

**Issue by szriru** [mallorbc/whisper_mic#53]
For windows 11, it seems "ctrl+c" doesn't stop the process completely.

[Reproduct process]
1. pip install of whisper_mic
2. "whisper_mic --loop"
3. wait for the initialization
4. "Ctrl+c"
5. "Aborted!" shows in the command line. but the command line doesn't start to accept new commands.
(chatgpt says "Aborted!" is related to the operating system or the C runtime library btw.)

**Comment by mallorbc** [comment]
fixed in latest PR
