### ISSUE TITLE
Error while using the save_file to save the transcribed data

### ISSUE THREAD

**Issue by overlordiam** [mallorbc/whisper_mic#56]
<img width="679" alt="image" src="https://github.com/mallorbc/whisper_mic/assets/64598584/f6219e64-1c8c-4c55-940f-5d9ded9f7822">

Not sure if it is a system issue. @mallorbc I do not see the code to save the transcribed file anywhere. Am I missing something?

**Comment by mallorbc** [comment]
fixed thanks to you!
