### ISSUE TITLE
Thanks for this project

### ISSUE THREAD

**Issue by shervinemami** [mallorbc/whisper_mic#6]
Hi, I just wanted to say Thanks for posting this sample app, I used it as part of a voice coding system (speech recognition for software developers) that I'm currently using to control my computer without a keyboard due to RSI issues: https://github.com/daanzu/kaldi-active-grammar/pull/73

**Comment by mallorbc** [comment]
Glad you found it helpful!  Thanks for sharing how you are using my code elsewhere!  Cool to see.
