### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by DillonHHH** [mallorbc/whisper_mic#9]
I'm not sure how to fix this, but the issue lies with this line:
`            audio_clip = AudioSegment.from_file(data)
`
used this code:
  
```
print("test1")
audio = r.listen(source)
print("test2")
data = io.BytesIO(audio.get_wav_data())
print(data)
print("\n\n\n")
audio_clip = AudioSegment.from_file(data)
print("test4")
```

got this printout (excluding the error):

```
Say something!
test1
test2
<_io.BytesIO object at 0x000002889399A0C0>

```
not sure if this is related:

```
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

```

I've installed ffmpeg, not sure why I'm getting that

**Comment by mallorbc** [comment]
You need to install ffmpeg and add it to the path.  Being on the path is crucial.  You have to restart your PC after adding it to the path.

**Comment by DillonHHH** [comment]
Thank you!
